document.writeln(" <nav class=\'navbar navbar-expand-lg navbar-dark bg-blue w-100 \' style=\'position: fixed; z-index: 1200; \'>");
document.writeln("        <!-- width如果是用百分比設定就會造成排版被擠爆 -->");
document.writeln("        <a class=\'navbar-brand \' href=\'#\'>停車場查詢系統");
document.writeln("            <!-- <img src=\'https://i.imgur.com/Rp9bUCe.png\' width=\'40\' class=\'d-inline-block\'> -->");
document.writeln("            <i class=\'fas fa-parking\'></i>");
document.writeln("        </a>");
document.writeln("");
document.writeln("        <!-- 手機大小時出現的漢堡 -->");
document.writeln("        <button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#navbarSupportedContent\'");
document.writeln("            aria-controls=\'navbarSupportedContent\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("            <span class=\'navbar-toggler-icon\'></span>");
document.writeln("        </button>");
document.writeln("");
document.writeln("        <div class=\'collapse navbar-collapse\' id=\'navbarSupportedContent\'>");
document.writeln("            <ul class=\'navbar-nav mr-auto\'>");
document.writeln("                <!-- <li class=\'nav-item dropdown\'>");
document.writeln("                    <a class=\'nav-link dropdown-toggle\' href=\'#\' id=\'navbarDropdownMenuLink\' role=\'button\'");
document.writeln("                        data-toggle=\'dropdown\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                        社團列表");
document.writeln("                    </a>");
document.writeln("                    <div class=\'dropdown-menu\' aria-labelledby=\'navbarDropdownMenuLink\'>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>國術社</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>登山社</a>");
document.writeln("                        <a class=\'dropdown-item\' href=\'#\'>劍道社</a>");
document.writeln("                    </div>");
document.writeln("                </li> -->");
document.writeln("                <li class=\'nav-item active\'>");
document.writeln("                    <a class=\'nav-link\' href=\'./taipei.html\'>台北市 <span class=\'sr-only\'>(current)</span></a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item active\'>");
document.writeln("                    <a class=\'nav-link\' href=\'./chiayi.html\'>嘉義縣 <span class=\'sr-only\'>(current)</span></a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item active\'>");
document.writeln("                    <a class=\'nav-link\' href=\'./Hsinchu.html\'>新竹市 <span class=\'sr-only\'>(current)</span></a>");
document.writeln("                </li>");
document.writeln("");
document.writeln("                <!-- <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'#\'>Link</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link disabled\' href=\'#\'>Disabled</a>");
document.writeln("                </li> -->");
document.writeln("            </ul>");
document.writeln("            <!-- <form class=\'form-inline my-2 my-lg-0\'>");
document.writeln("                <input id=\'myInput\' class=\'form-control mr-sm-2\' type=\'text\' placeholder=\'Search\' aria-label=\'Search\'>");
document.writeln("                <button class=\'btn btn-outline-light my-2 my-sm-0 \' type=\'submit\'>Search</button>");
document.writeln("            </form> -->");
document.writeln("        </div>");
document.writeln("    </nav>");